repositoryModernizer:
  # groupId to be used for newly created packages
  groupId: com.adobe.summit23.l717
  # information about parent pom
  parentPom:
    # absolute path to the parent pom file
    path: /Users/murugull/MySpace/CASH/Summit2023/L717-lab/pom.xml
    # the artifactId to be set for the parent pom
    artifactId: aem-cs-transition
    # the application title to be set for the parent pom
    appTitle: Summit L771 Parent
    # version to be to be set for the parent pom
    version: 1.0.0-SNAPSHOT
  # information required for all and analyse packages
  all:
    # prefix that is to be used to set the artifactId for all and analyse packages
    artifactId: aem-cs-transition
    # application title
    appTitle: Summit L771 CS Code Repository
    # version to be set for all pom
    version: 1.0.0-SNAPSHOT
  # information about projects (expects an array of project information)
  # NOTE : For multiple projects create separate copies of the info section for each project
  projects:
    - # absolute path to the XYZ project folder
      projectPath: /Users/murugull/MySpace/CASH/Summit2023/L717-lab
      # Array of relative path(s) (w.r.t. the project folder) to the existing content package(s) that needs to be restructured.
      # NOTE : only content packages are expected here, NOT bundle/jar artifacts
      existingContentPackageFolder:
        - /ui.apps
        - /ui.content
      #  - /ui.permissions
      # relative path (w.r.t. the existing content package folder) to the filter.xml file
      # (If not specified, default path `/src/main/content/META-INF/vault/filter.xml` will be used.)
      relativePathToExistingFilterXml:
      # relative path (w.r.t. the existing content package folder) to the jcr_root directory
      # (If not specified, default path `/src/main/content/jcr_root` will be used)
      relativePathToExistingJcrRoot:
      # prefix that is to be used to set the artifactId for newly created ui.apps and ui.content packages
      artifactId: aem-cs-transition
      # application title
      appTitle: Summit L771
      # application ID (will be used for config and package folder names)
      appId: aem-cs-transition
      # project specific version to be used for content packages
      version: 1.0.0-SNAPSHOT
      # Array of relative path(s) (w.r.t. the project folder) to the existing code bundles (will be embedded in the all package).
      coreBundles:
        - /core
      #    - /api
      # OSGi config folders that need to be renamed.
      # The existing/source OSGi config folder PATH (JCR path starting from '/apps') is expected as key
      # and the replacement OSGi folder NAME is expected as value. See examples below :
      #    /apps/xyz/config.prod : config.publish.prod
      #    /apps/system/config.author.dev1 : config.author.dev
      #    /apps/system/config.author.dev2 : config.author.dev
      # NOTE :
      #    1. All OSGi config folders under the same path and with same replacement name will be MERGED
      #       (as configured in above example).
      #    2. If there exists OSGi config files with the same pid/filename in more than one config folders
      #       which are to be merged, they will not be overwritten. A warning regrading the same will be
      #       generated in the summary report and result log file. User would need to manually evaluate
      #       which config to persist
      osgiFoldersToRename:
        /apps/aem-cs-transition/config.author: config.author.dev
        #/apps/xyz/config.dev2: config.author.dev
        /apps/system/config.author.localdev: config.author.dev
        /apps/system/config.author.dev1: config.author.dev
        /apps/system/config.prod: config.publish.prod
        /apps/system/config.publish: config.publish.prod
